#!/bin/zsh

killall polybar
killall xfce4-notifyd

CUSTOM_PATH=$PATH:~/.local/wm/bin:~/.local/wm/i3/:~/.local/wm/polybar_helpers

# Notification
/usr/lib/xfce4/notifyd/xfce4-notifyd &

# Background
feh --randommize --bg-fill $HOME/Pictures/wallpapers/

# Polybar
$HOME/.local/wm/polybar_helpers/init-tab
PATH=$CUSTOM_PATH polybar -r top &
PATH=$CUSTOM_PATH polybar -r down &

# Transparency
compton &

# Sound notification
volnoti &

# Network manager
nm-applet &

# Redshift
(/usr/lib/geoclue-2.0/demos/agent| redshift-gtk) &

# Clipboard
parcellite &

#Keyboard manager
fcitx &

# Authentification agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start)
export SSH_AUTH_SOCK
